[package]
name = "neetcode"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
itertools = "0.12.0"
serde = "1.0.193"
serde_json = "1.0.108"

[profile.release]
opt-level = 2
debug = false
